config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'
  get 'feedback/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users

  resources :tests, only: [:index] do
    resources :questions, except: [:index, :show], shallow: true do
      resources :answers, except: [:index, :show], shallow: true
    end

    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: [:new, :create]

  resources :badges, only: [:index]

  namespace :admin do
    resources :tests, except: [:show] do
      patch :update_inline, on: :member

      resources :questions, except: [:index, :show], shallow: true do
        resources :answers, except: [:index, :show], shallow: true
      end
    end

    resources :gists, only: [:index]

    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :test_passage, optional: true

  validates :title, :icon_url, :rule_type, :rule_value, presence: true

  RULES = {
    all_in_category: Category.pluck(:title),
    all_in_level: Test.pluck(:level).uniq,
    number_of_tries: [ 1 ]
  }.freeze
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :badge, only: [:edit, :update, :destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.done', badge: @badge.title)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('.done', badge: @badge.title)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    
    redirect_to admin_badges_path, notice: t('.done', badge: @badge.title)
  end

  private

  def badge
    @badge = Badge.find(params[:id]) if params[:id]
  end

  def badge_params
    params.require(:badge).permit(:title, :icon_url, :rule_type, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <p class="form__field">
    <%= form.label :title  %>
    <%= form.text_field :title, id: :badge_title %>
  </p>

  <p class="form__field">
    <%= form.label :icon_url  %>
    <%= form.url_field :icon_url, id: :badge_icon_url %>
  </p>

  <p class="form__field">
    <%= form.label :rule_type  %>
    <%= form.select :rule_type, Badge::RULES.keys, { include_blank: t('.select') } %>
  </p>

  <p class="form__field">
    <%= form.label :rule_value  %>
    <%= form.select :rule_value,
                    Badge::RULES.flat_map { |k, vs| vs.map { |v| [v, { 'data-rule-type': k }] } },
                    { include_blank: t('.select') },
                    { disabled: true }
    %>
  </p>

  <p class="form__action"> <%= form.submit %> </p>
<% end %>

app/views/admin/badges/edit.html.erb
<%= render 'shared/errors', resource: @badge %>

<div class="form">
  <h1 class="form__title"> <%= t('.header') %> </h1>

  <%= render 'form' %>
</div>

app/views/admin/badges/index.html.erb
<%= render 'shared/errors', resource: @badge %>

<div class="table">
  <h2 class="table__title"> <%= t('.header') %> </h2>

  <table class="table__content">
    <thead>
      <tr>
        <th> <%= t('.title') %></th>
        <th> <%= t('.icon') %> </th>
        <th> <%= t('.rule_type') %> </th>
        <th> <%= t('.rule_value') %> </th>
      </tr>
    </thead>

    <tbody>
      <% @badges.each do |badge| %>
        <tr>
          <td> <%= badge.title %> </td>
          <td> <%= image_tag(badge.icon_url, size: "30x30") %> </td>
          <td> <%= badge.rule_type %> </td>
          <td> <%= badge.rule_value %> </td>
          <td> <%= link_to t('.edit'), edit_admin_badge_path(badge), class: 'table__subaction' %> </td>
          <td> <%= link_to t('.delete'), admin_badge_path(badge), method: :delete, class: 'table__subaction' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to t('.new'), new_admin_badge_path, class: 'table__action' %>
</div>

app/views/admin/badges/new.html.erb
<%= render 'shared/errors', resource: @badge %>

<div class="form">
  <h1 class="form__title"> <%= t('.header') %> </h1>

  <%= render 'form' %>
</div>