config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'
  get 'feedback/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users

  resources :tests, only: [:index] do
    resources :questions, except: [:index, :show], shallow: true do
      resources :answers, except: [:index, :show], shallow: true
    end

    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: [:new, :create]

  resources :badges, only: [:index]

  namespace :admin do
    resources :tests, except: [:show] do
      patch :update_inline, on: :member

      resources :questions, except: [:index, :show], shallow: true do
        resources :answers, except: [:index, :show], shallow: true
      end
    end

    resources :gists, only: [:index]

    resources :badges
  end
end

app/models/admin.rb
class Admin < User

end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_ANSWERS_COUNT = 4

  belongs_to :question

  scope :correct, -> { where(is_correct: true) }

  validates :body, presence: true
  validate :validate_answers_count

  private

  def validate_answers_count
    errors.add(:question) if question.answers.count >= MAX_ANSWERS_COUNT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :test_passage, optional: true

  validates :title, :icon_url, :rule_type, :rule_value, presence: true

  RULES = {
    all_in_category: Category.pluck(:title),
    all_in_level: Test.pluck(:level).uniq,
    number_of_tries: [ 1 ]
  }.freeze
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :user
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, class_name: 'TestPassage', foreign_key: 'current_question_id'
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  
  has_many :users, through: :test_passages

  default_scope { order(:title) }

  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: [:level, :category_id] }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_create :capitalize_title

  # scope :easy, -> { where(level: 0..1) }
  # scope :medium, -> { where(level: 2..4) }
  # scope :hard, -> { where(level: 5..Float::INFINITY) }

  # scope :by_category_title, -> (category_title) { joins(:category).where(categories: { title: category_title }) }

  def capitalize_title
    self.title = title.split.map(&:capitalize).join(' ')
  end

  # def self.desc_tests_titles_by_category_title(category_title)
  #   by_category_title(category_title).order(title: :desc).pluck(:title)
  # end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges, dependent: :destroy

  before_validation :before_validation_set_first_question, on: :create

  SUCCESS_RATE_LEVEL = 85

  def accept!(answer_ids)
    self.correct_questions_count += 1 if correct_answers.ids.sort == answer_ids.map(&:to_i).sort

    self.current_question = next_question

    save
  end

  def timer
    remaining_time = test.timer - (Time.current - created_at).to_i

    remaining_time > 0 ? remaining_time : 0
  end

  def timer_expired?
    test.timer && timer == 0
  end
  
  def completed?
    current_question.nil?
  end

  def result
    correct_questions_count
  end

  def test_result_rate
    (correct_questions_count.to_f / questions.size * 100).round
  end

  def test_progress
    ((current_question_serial_number.to_f - 1) / questions.size * 100).round
  end

  def success?
    test_result_rate >= SUCCESS_RATE_LEVEL
  end

  def current_question_serial_number
    questions.index(current_question) + 1
  end

  private

  def questions
    test.questions.order(:id)
  end

  def next_question
    questions.where('id > ?', current_question.id).first
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_validation_set_first_question
    self.current_question = questions.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :confirmable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id'

  has_many :test_passages
  has_many :passed_tests, through: :test_passages, source: :test

  has_many :feedbacks

  has_many :gists

  has_and_belongs_to_many :badges

  validates_presence_of :first_name, :last_name
  validates_confirmation_of :password

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    passed_tests << test

    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = current_user.feedbacks.new
  end

  def create
    @feedback = current_user.feedbacks.new(feedback_params)

    if @feedback.save
      FeedbacksMailer.send_feedback(@feedback).deliver_now

      redirect_to root_path, notice: t('.success')
    else
      render :new
    end
  end

  def feedback_params
    params.require(:feedback).permit(:body)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])

    test_passage = current_user.test_passage(@test)

    redirect_to test_passage_path(test_passage)
  end

  def rescue_with_test_not_found
    redirect_to root_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.now.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_messages
    safe_join(flash.map { |type, message| content_tag :p, message.html_safe, class: "flash_#{type}" })
  end

  def main_page_path
    current_user.admin? ? admin_tests_path : root_path
  end
  
  def global_locale
    @translations ||= I18n.backend.send(:translations)
    @translations[I18n.locale].with_indifferent_access
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_text
    @test_passage.success? ? t('.success') : t('.fail')
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def isFilled?(test)
    test.questions.count > 0 && test.questions.all? { |question| question.answers.count > 0 }
  end
end

app/views/admin/_nav.html.erb
<nav class="nav">
  <% unless current_page?(admin_tests_path) %>
    <%= link_to t('.tests_list'), admin_tests_path %>
  <% end %>

  <% unless current_page?(admin_gists_path) %>
    <%= link_to t('.gists_list'), admin_gists_path %>
  <% end %>

  <% unless current_page?(admin_badges_path) %>
    <%= link_to t('.badges_list'), admin_badges_path %>
  <% end %>
</nav> 

app/views/layouts/_flash.html.erb
<div class="flash">
  <%= flash_messages %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <% if user_signed_in? %>

    <%= link_to t('feedback'), new_feedback_path, class: "footer__feedback" %>

  <% end %>

  <div class="footer__about">
    <span class="footer__year"> © <%= current_year %> </span>

    <%= link_to t('logo'), github_url('SonyaOrlova', 'ROR-basic-Test-Guru'), target: '_blank', class: 'footer__link' %>

    <p class="project-info">
      <%= t('project-info') %>
      <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank', class: 'footer__link' %>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <%= link_to t('logo'), root_path, class: "header__logo" %>

  <% if user_signed_in? %>

    <div class="header__greeting">
      <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
    </div>

    <nav class="header__navigation">
      <% if current_user.admin? %>
        <%= link_to t('admin-panel'),
                    admin_tests_path,
                    class: request.path.start_with?("/admin") ?
                      "header__admin-panel header__admin-panel_active" :
                      "header__admin-panel"
        %>
      <% end %>

      <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: "header__bar-link" %>
    </nav>

    <% else %>
      <nav class="header__navigation">
        <% if request.path != new_user_session_path %>

          <%= link_to t('login'), new_user_session_path, class: "header__bar-link" %>

        <% end %>

        <% if request.path != new_user_registration_path %>

          <%= link_to t('sign-up'), new_user_registration_path, class: "header__bar-link" %>

        <% end %>
      </nav>
    <% end %>
  </nav>
</div>

app/views/layouts/_nav.html.erb
<nav class="nav">
  <% unless current_page?(badges_path) %>
    <%= link_to t('.badges_list'), badges_path %>
  <% end %>
</nav> 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>RORBasicTestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <%= render 'admin/nav' %>
      <%= render 'layouts/flash' %>

      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>

  <script type="text/javascript">
    window.I18n = <%= global_locale.to_json.html_safe %>
  </script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>RORBasicTestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <%= render 'layouts/nav' %>
      <%= render 'layouts/flash' %>

      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>

  <script type="text/javascript">
    window.I18n = <%= global_locale.to_json.html_safe %>
  </script>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <div class="errors">
    <h3 class="errors__title">
      <%= t('.info', count: resource.errors.count).capitalize %>
    </h3>
    <ul class="errors__list">
      <% resource.errors.full_messages.each do |message| %>
        <li class="errors__item">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>