config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'
  get 'feedback/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users

  resources :tests, only: [:index] do
    resources :questions, except: [:index, :show], shallow: true do
      resources :answers, except: [:index, :show], shallow: true
    end

    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: [:new, :create]

  resources :badges, only: [:index]

  namespace :admin do
    resources :tests, except: [:show] do
      patch :update_inline, on: :member

      resources :questions, except: [:index, :show], shallow: true do
        resources :answers, except: [:index, :show], shallow: true
      end
    end

    resources :gists, only: [:index]

    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, class_name: 'TestPassage', foreign_key: 'current_question_id'
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges, dependent: :destroy

  before_validation :before_validation_set_first_question, on: :create

  SUCCESS_RATE_LEVEL = 85

  def accept!(answer_ids)
    self.correct_questions_count += 1 if correct_answers.ids.sort == answer_ids.map(&:to_i).sort

    self.current_question = next_question

    save
  end

  def timer
    remaining_time = test.timer - (Time.current - created_at).to_i

    remaining_time > 0 ? remaining_time : 0
  end

  def timer_expired?
    test.timer && timer == 0
  end
  
  def completed?
    current_question.nil?
  end

  def result
    correct_questions_count
  end

  def test_result_rate
    (correct_questions_count.to_f / questions.size * 100).round
  end

  def test_progress
    ((current_question_serial_number.to_f - 1) / questions.size * 100).round
  end

  def success?
    test_result_rate >= SUCCESS_RATE_LEVEL
  end

  def current_question_serial_number
    questions.index(current_question) + 1
  end

  private

  def questions
    test.questions.order(:id)
  end

  def next_question
    questions.where('id > ?', current_question.id).first
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_validation_set_first_question
    self.current_question = questions.first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :test_passage

  def show
    redirect_to result_test_passage_path(@test_passage) if @test_passage.timer_expired? || @test_passage.passed
  end

  def update
    unless params[:answer_ids].present?
      redirect_to test_passage_path(@test_passage), notice: t('.no_answer_given')
      
      return
    end

    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      @test_passage.update(passed: true) if @test_passage.success?

      TestsMailer.completed_test(@test_passage).deliver_now

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end

  end

  def result
    BadgeService.new(@test_passage).getBadges

    @badges = test_passage.badges
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      response = result.response
      
      current_user.gists.create(question_id: @test_passage.current_question.id, gist_url: response.html_url)

      flash[:notice] = t('.success', gist_link: view_context.link_to(response.id, response.html_url, target: '_blank'))
    else
      flash[:alert] = t('.fail')
    end

    redirect_to @test_passage
  end

  private

  def test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_text
    @test_passage.success? ? t('.success') : t('.fail')
  end
end

app/views/test_passages/result.html.erb
<% @result = @test_passage.success? %>

<div class="test-passage-result test-passage-result_<%= @test_passage.success? ? 'success' : 'fail'%>">
  <h1 class="test-passage-result__title"> <%= result_text %> </h1>

  <h2 class="test-passage-result__rate">
    Процент успеха:
    <%= @test_passage.test_result_rate %>
  </h2>

  <% if @badges.present? %>
    <div class="test-passage-result__badges">
      <h3> <%= t('.badges') %>: </h3>

      <%= render 'shared/badges/badges_list', badges: @badges %>
    </div>
  <% end %>
</div>

app/views/test_passages/show.html.erb
<div class="test-passage">
  <h1 class="test-passage__title">
    <%= t('.title') %>
    <span class="test-passage__title-text">
      <%= @test_passage.test.title %>
    </span>
  </h1>
  
  <p class="test-passage__info">
    <%= t('.info') %>
    <%= @test_passage.current_question_serial_number %> / <%= @test_passage.test.questions.count %>
  </p>

  <div class="test-passage__progress-bar">
    <%= content_tag :p, '', class: 'test-passage__progress', data: { test_progress: @test_passage.test_progress } %>
  </div>

  <% if @test_passage.test.timer %>
    <%= content_tag :p, '', class: 'test-passage__timer', data: { timer: @test_passage.timer } do %>
      <span class="test-passage__timer-minutes"></span>
      :
      <span class="test-passage__timer-seconds"></span>
    <% end %>
  <% end %>

  <h2 class="test-passage__question"> <%= @test_passage.current_question.body %> </h2>
  <%= form_with url: test_passage_path(@test_passage), method: :put, local: true, class: 'test-passage__form' do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |cb|%>
      <p class="test-passage__answer">
        <%= cb.check_box %>
        <%= cb.label %>
      </p>
    <% end %>

    <%= form.submit t('.submit'), class: 'test-passage__action' %>
  <% end %>

  <%= link_to t('.github_gist'), gist_test_passage_path(@test_passage), method: :post, class: 'test-passage__github-gist' %>
</div>